//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAhorroPrestamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuotaP
    {
        public int id_cuota { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> MontoCuota { get; set; }
        public Nullable<double> FechaEfectivaCuota { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_prestamo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual prestamos prestamos { get; set; }
    }
}
