//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAhorroPrestamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garantia
    {
        public int id_garantia { get; set; }
        public string CodigoGarantia { get; set; }
        public string TipoGarantia { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> id_prestamo { get; set; }
    
        public virtual prestamos prestamos { get; set; }
    }
}
