//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAhorroPrestamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inversion
    {
        public int id_inversion { get; set; }
        public string CodigoInversion { get; set; }
        public Nullable<double> MontoInversion { get; set; }
        public string TasaInteres { get; set; }
        public Nullable<System.DateTime> FechaInversion { get; set; }
        public Nullable<System.DateTime> FechaRembolso { get; set; }
        public Nullable<int> id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
