//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAhorroPrestamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_usuario
    {
        public int id_rol_usuario { get; set; }
        public string rol { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
