//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAhorroPrestamos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Cliente2
    {
        public int id_rol_cliente { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_rol { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
